
server:
#  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
#      限制文件上传的大小
  servlet:
    multipart:
      max-file-size: 512000  # 文件上传大小限制500kb
      max-request-size: 51200
  profiles:
#    active: prod
    active: dev
    # 请求大小限制为500kb
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wonder4work.bean
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
